### ISSUE TITLE
pivot/plot/data options icons are not available in the plot window

### ISSUE THREAD

**Issue by jllipatz** [ryantimpe/rspivot#6]
The icon to go back to the pivot page is not available in the plot page : one must leave with done or cancel and go back at the starting point.
Additionnaly, would it be possible to enlarge (or give the possibility to enlarge) the whole window?

**Comment by ryantimpe** [comment]
I'm not sure about the icons disappearing - I can't reproduce that error.

I just added the option to open up the pivot table in your web browser. Use `launch.browser = TRUE` in the function call to open the window in your web browser.
